### ISSUE TITLE
Camera view never shows

### ISSUE THREAD

**Issue by Kostecki** [TheWirv/react-barcode-scanner#1]
Came across this fork while looking for a combination of react/camera/barcode that actually works and yours seemed to be the most promising. I can't get it to work though.

On a completely fresh craete-react-app-install with nothing but the example code the "no camera"-image shows, there's a flash and then nothing. All while the red dot in the tab indicating camera access also flashes briefly.

It looks like this:

https://user-images.githubusercontent.com/9408523/222992959-bc9a59cc-136e-40b5-bc90-5f10a69eae8c.mov

No errors in the console and nothing indicating anything.

Am i doing something wrong here?

My App.jsx, although not very exciting, looks like this:
```
// App.jsx

import { useState } from "react";
import { BarcodeScanner } from "@thewirv/react-barcode-scanner";

const App = (props) => {
  const [data, setData] = useState("No result");

  return (
    <div style={{ height: "250px", width: "250px" }}>
      <BarcodeScanner
        onSuccess={(text) => setData(text)}
        onError={(error) => {
          if (error) {
            console.error(error.message);
          }
        }}
        constraints={{ facingMode: "environment" }}
        onLoad={() => console.log("Video feed has loaded!")}
        containerStyle={{ width: "100%" }}
      />
      <p>{data}</p>
    </div>
  );
};

export default App;

```

**Comment by salehmalik121** [comment]
Any Solutions

**Comment by quang-m-nguyen** [comment]
@Kostecki @salehmalik121 you guys likely need to go to Chrome settings and enable the camera for localhost.  The camera is disabled by default

**Comment by thewirv** [comment]
If this issue has been clarified due to @quang-m-nguyen's comment, I'll close this.
